### ISSUE TITLE
error not handled when no id is returned with biomaRt

### ISSUE THREAD

**Issue by nsdevoss** [lasseignelab/CoSIA#29]
cosia_object <- CoSIAn(
    gene_set = "FBgn0003975",
    i_species="d_melanogaster",
    o_species="r_norvegicus",
    input_id="Ensembl_id",
    o_ids= "Ensembl_id",
    mapping_tool="biomaRt",
    ortholog_database = "HomoloGene",
    map_tissues = "",
    map_species = "",
    metric_type=""
  )

instead of throwing the "No orthologs were found for all genes in one of the species." warning, the error Error in biomaRt::getBM(attributes = c(output_ids, "entrezgene_id"), filters = "entrezgene_id",  : 
  Values argument contains no data. is thrown.

**Comment by anishahaldar** [comment]
It throws both errors most likely due to the inability to find an ortholog gene for this ensembl id in rat.
