### ISSUE TITLE
Duplicate Rows from getConversions

### ISSUE THREAD

**Issue by nsdevoss** [lasseignelab/CoSIA#50]
```
cosia_object <- CoSIAn(
  gene_set = c("ENSG00000172315",
               "ENSG00000087460",
               "ENSG00000049759",
               "ENSG00000088256",
               "ENSG00000102144",
               "ENSG00000072501",
               "ENSG00000148459",
               "ENSG00000198931",
               "ENSG00000278229",
               "ENSG00000278229",
               "ENSG00000182774",
               "ENSG00000182774",
               "ENSG00000081479",
               "ENSG00000157483",
               "ENSG00000113924",
               "ENSG00000171863",
               "ENSG00000025796",
               "ENSG00000011201"),
  i_species="h_sapiens",
  o_species="m_musculus",
  input_id="Ensembl_id",
  output_ids="Ensembl_id",
  mapping_tool="annotationDBI",
  ortholog_database = "HomoloGene",
  map_tissues = "",
  map_species = "",
  metric_type=""
)
getConversions(cosia_object)@converted_id
```
There are approximately 500 rows with the same results. Might want to make sure that there aren't duplicates in the returned dataframe. Note, that I don't think this a result of a gene mapping to several orthologs.

**Comment by adc0032** [comment]
@anishahaldar  @nsdevoss 

The issues with duplicates is not just an artifact of duplications in the geneset. 
EJ used CoSIA.Shiny with a unique list of 99 human Ensembl ids and converted them to mouse. This resulted in a total number of 295 entries. 

I verified this using her shared geneset and it returned 295 entries in CoSIA locally. 

I am reopening this issues, as it is not resolved. 

Places to consider looking to address this error: 
There is code to remove Version information from input ids, but is that happening when we convert to another species?
There is code to remove duplicated input ids, but should there be a second unique run after the data is filter down to the ids of interest?
